"""Updated database

Revision ID: 4c7e3028161a
Revises: 954652c52dec
Create Date: 2026-03-26 11:00:53.664698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7e3028161a'
down_revision: Union[str, Sequence[str], None] = '954652c52dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('Users', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Users', 'is_active')
    # ### end Alembic commands ###
