"""enhanced user details

Revision ID: 954652c52dec
Revises: fd2b8035fbf9
Create Date: 2026-03-26 09:03:13.215404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954652c52dec'
down_revision: Union[str, Sequence[str], None] = 'fd2b8035fbf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('Users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('Users', sa.Column('DOB', sa.Date(), nullable=False))
    op.add_column('Users', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'status')
    op.drop_column('Users', 'DOB')
    op.drop_column('Users', 'last_name')
    op.drop_column('Users', 'first_name')
    # ### end Alembic commands ###
